# AquaGenomeAI - Deep-Sea Genomic Analysis Configuration

# Database Configuration
database:
  name: "AquaGenome"
  collections:
    sequences: "sequence"
    taxa: "taxon"
    samples: "sample"
    links: "sequence-taxon"
  
  # Vector index settings
  vector_index:
    dimension: 768  # DNABERT-2 embedding dimension
    metric: "cosine"
    nLists: 100

# Model Configuration
models:
  # DNABERT-2 for DNA embeddings
  dnabert:
    name: "zhihan1996/DNABERT-2-117M"
    max_length: 512
    batch_size: 32
    device: "cpu"  # or "cuda" if GPU available
    kmer: 6
  
  # FAISS for similarity search
  faiss:
    index_type: "IndexFlatIP"  # Options: IndexFlatIP, IndexFlatL2, IVF,PQ
    metric: "cosine"
    nlist: 1024
    nprobe: 10
    use_gpu: false

# Similarity & Classification Thresholds
similarity:
  high_confidence: 0.85      # > 0.85: Known species (high confidence)
  medium_confidence: 0.70    # 0.70-0.85: Potential match (verify)
  low_confidence: 0.70       # < 0.70: Unknown/novel candidate
  top_k: 10                  # Number of similar sequences to return

# BLAST Configuration
blast:
  enabled: true              # Run BLAST for verification
  database: "nt"             # or "16S_ribosomal_RNA" for targeted
  e_value: 1e-5
  max_target_seqs: 5
  num_threads: 4
  min_identity: 70           # Minimum % identity
  min_coverage: 50           # Minimum % query coverage

# Clustering Configuration (for unknown sequences)
clustering:
  # UMAP dimensionality reduction
  umap:
    n_neighbors: 15
    min_dist: 0.1
    n_components: 2
    metric: "cosine"
    random_state: 42
  
  # HDBSCAN density-based clustering
  hdbscan:
    min_cluster_size: 10
    min_samples: 5
    cluster_selection_epsilon: 0.0
    metric: "euclidean"
  
  # Cluster validation
  min_silhouette: 0.3        # Minimum silhouette score

# NCBI Data Fetching
ncbi:
  databases:
    - "nucleotide"
    - "16S_ribosomal_RNA"
    - "18S_ribosomal_RNA"
  email: "your.email@example.com"  # REQUIRED for NCBI API
  max_sequences: 1000
  rate_limit: 3              # requests per second

# Sequence Preprocessing
preprocessing:
  # Quality control
  min_quality_score: 20
  min_length: 100
  max_length: 10000
  
  # Deduplication
  remove_duplicates: true
  duplicate_threshold: 0.99  # 99% identity = duplicate
  
  # Filtering
  remove_ambiguous: true     # Remove sequences with many N's
  max_n_percent: 5           # Max % of N's allowed

# Phylogenetic Analysis
phylogenetics:
  alignment_tool: "mafft"    # Options: mafft, muscle, clustal
  tree_method: "iqtree"      # Options: iqtree, fasttree, raxml
  bootstrap_replicates: 1000
  model: "GTR+G"             # Substitution model

# Exa Literature Search
exa:
  enabled: true
  num_results: 5
  search_type: "neural"      # Options: neural, keyword
  focus_domains: 
    - "ncbi.nlm.nih.gov"
    - "nature.com"
    - "science.org"
    - "biorxiv.org"

# Visualization
visualization:
  # Sequence alignment
  alignment:
    max_sequences: 50
    color_scheme: "clustal"
  
  # Phylogenetic trees
  tree:
    format: "newick"
    layout: "rectangular"    # Options: rectangular, circular, radial
    show_bootstrap: true
  
  # Cluster plots
  clusters:
    plot_format: "png"
    dpi: 300
    colormap: "viridis"

# Agent & LLM Configuration
agent:
  llm_provider: "google"     # Google Gemini
  model: "gemini-1.5-flash"
  temperature: 0.7
  max_tokens: 2000
  
  # Tool calling
  max_iterations: 10
  enable_memory: true
  memory_db: "chat_history.db"
  
  # Context management
  max_context_messages: 20
  summarize_threshold: 15

# Logging
logging:
  level: "INFO"              # Options: DEBUG, INFO, WARNING, ERROR
  file: "logs/aquagenome.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Track metrics
  track_tool_usage: true
  track_similarity_scores: true
  track_processing_time: true

# Performance
performance:
  cache_embeddings: true
  cache_ttl: 3600            # seconds
  max_workers: 4
  batch_processing: true
  chunk_size: 1000           # sequences per batch
