version: "3.9"
services:
  arangodb:
    container_name: aquagenome_db
    image: arangodb/arangodb:3.12.4
    restart: unless-stopped
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    ports:
      - "8529:8529"
    command: ["arangod", "--experimental-vector-index", "true"]
    volumes:
      - aquagenome_data:/var/lib/arangodb3

volumes:
  aquagenome_data:

