[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[global]
environment = "production"

[theme] 
base="dark"
primaryColor="#1d1d1d"
secondaryColor="#323232"
backgroundColor="#1d1d1d"
SecondaryBackgroundColor="#323232"
textColor="#B9B9B9"
